### ISSUE TITLE
Correct Auth URL

### ISSUE THREAD

**Issue by marcelodeandrade** [RichWeber/yii2-twitter#1]
Hello, @RichWeber! 

The current URL for Auth is `https://api.twitter.com/oauth2/token` when should be `https://api.twitter.com/oauth/authenticate`

**Comment by RichWeber** [comment]
Hi, @marcelodeandrade !

Are you sure?

GET oauth/authorize - `https://api.twitter.com/oauth/authenticate`

This method fulfills [Section 6.2](http://oauth.net/core/1.0/#auth_step2) of the **[OAuth 1.0](http://oauth.net/core/1.0/#auth_step2)** authentication flow.

POST oauth2/token - `https://api.twitter.com/oauth2/token`

Allows a registered application to obtain an **OAuth 2** Bearer Token, which can be used to make API requests on an application’s own behalf, without a user context. This is called Application-only authentication.

**Comment by marcelodeandrade** [comment]
Well, when use the `POST oauth2/token - https://api.twitter.com/oauth2/token` Twitter is blocking your own API:

> Refused to apply inline style because it violates the following Content Security Policy directive: "style-src https://abs.twimg.com https://abs-0.twimg.com". Either the 'unsafe-inline' keyword, a hash ('sha256-4Su6mBWzEIFnH4pAGMOuaeBrstwJN4Z3pq/s1Kn4/KQ='), or a nonce ('nonce-...') is required to enable inline execution.
> 
> https://api.twitter.com/oauth2/token Failed to load resource: the server responded with a status of 400 ()

And i can't connect with it

**Comment by newscloud** [comment]
I'm getting this too 

Refused to apply inline style because it violates the following Content Security Policy directive: "style-src https://abs.twimg.com https://abs-0.twimg.com". Either the 'unsafe-inline' keyword, a hash ('sha256-4Su6JN4Z3pq/s1Kn4/KQ='), or a nonce ('nonce-...') is required to enable inline execution.

token:1 Refused to load the image 'https://api.twitter.com/favicon.ico' because it violates the following Content Security Policy directive: "img-src https://abs.twimg.com https://*.twimg.com https://pbs.twimg.com data:".

**Comment by VictorParraCant** [comment]
Hi @newscloud did you solved this issue? We are having the same problem. Thanks.

**Comment by wzup** [comment]
Same here.
Although I do not use `yii2-twitter`, I found the error here by googling the error string.
I use [PassportJS](http://passportjs.org/) for Twitter logins. But decided to leave a message also.

> authenticate:1 Refused to load the image 'https://api.twitter.com/favicon.ico' because it violates the following Content Security Policy directive: "img-src https://abs.twimg.com https://*.twimg.com https://pbs.twimg.com data:".

**Comment by ericlaw1979** [comment]
FWIW, the "Refused to apply inline style ... a hash ('sha256-4Su6mBWzEIFnH4pAGMOuaeBrstwJN4Z3pq/s1Kn4/KQ=')" message comes from Chrome's attempt to apply a default style to document responses that are interpreted as text. That default style lights up this warning. https://crbug.com/766965.
